sudo: required
services:
  - docker
before_ install:
  - docker build -t alemaqueda/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run alemaqueda/multi-docker npm run test -- --coverage
after_success:
  - docker build -t maqueda/multi-client ./client
  - docker build -t maqueda/multi-nginx ./nginx
  - docker build -t maqueda/muti-server ./server
  - docker build -t maqueda/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maqueda/multi-client
  - docker push maqueda/multi-nginx
  - docker push maqueda/muti-server
  - docker push maqueda/multi-worker

